version: "3.9"

services:
  postgres:
    build: "./db"
    restart: "always"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "test123"
    networks:
      - backend
  wallet:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      POSTGRES_DB: postgres
      PORT: "8080"
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "test123"
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - backend
networks:
  backend: 